### ISSUE TITLE
consulta codigo base

### ISSUE THREAD

**Issue by jmdelatorre** [IIC2113-2016-2/refactor-todos#4]
La idea es que copiemos los datos de este repo publico a nuestro repo privado cierto?

**Comment by lopezjurip** [comment]
Se supone que se le creó un repo privado a cada uno, revisa tus correos para la invitación 👍

**Comment by jmdelatorre** [comment]
Si si, pero pero el codigo base de este repo lo copiamos al otro repo nomas?

**Comment by lopezjurip** [comment]
Sí hagan eso. Mejor sería clonándolo y cambiando el remote, pero no es requisito:

``` sh
git clone https://github.com/IIC2113-2016-2/refactor-todos.git
cd refactor-todos
git remote remove origin
git remote add origin tarea-3-XX
git push --set-upstream origin master
```
